### ISSUE TITLE
How to initialize texteditor with custom initial text?

### ISSUE THREAD

**Issue by thibaultmeyer** [y-js/yjs#101]
Hello,

How to start with data from a default Database (like PostgreSQL); I don't want using YJS as storage, only as collaborative editor. In the following sample, I have set default data to "HELLO", but YJS erase data to replace it with empty value or not up to data data.

**question**
I'm using webrtc and the big question is, how to check if a room is populated (with users) and using data from this room. In other hand, if the room is empty, using data from my database (PostgreSQL) or data from the HTML page

**sample**
```
<script>
            Y({
                db: {
                    name: 'memory'
                },
                connector: {
                    name: 'webrtc',
                    room: 'ace-example'  // Room name
                },
                share: {
                    textarea: 'Text'
                }
            }).then(function (y) {
                y.db.requestTransaction(function *() {
                    var operations = yield* this.getOperations();
                    var deleteSet = yield* this.getDeleteSet();
                    console.log(operations);
                    console.log(deleteSet);
                });
                y.db.requestTransaction(function * () {
                    this.store.apply([]);
                });
                y.share.textarea.bind(document.querySelector('textarea'));
            })
        </script>
        <textarea cols="80" rows="40">HELLO</textarea>
```

**Comment by dmonad** [comment]
Hi @0xbaadf00d 
It is not possible to start with an agreed value. The only option you have is to write the initial value to the textarea object. But there are some problems that you need to solve yourself. For example, what happens if two users start a session at the same time? They will both write the initial value to the textarea object.

Here is an idea. If you keep track of the users that are active (e.g. with socket.io), the server can decide who writes the initial content to the room. The act keeping track is also handled by the signaling server. So in the future you could also adapt the signaling server to decide who writes the database content. I don't plan to implement a feature for that.

**Comment by 0xbaadf00d** [comment]
Hi @dmonad,

by using `y-websocket-server` (or any implementation), it could be, theoretically, to get the needed bahavior. By instance, the server, when it create a new room, it can search on a database to restore last state of the room (like a snapshot - server don't have to know all past modifications, only state that current restored text is the revisions 1). And when all users leave  the room, close it and free used memory.

Do you have any documentation about the communication protocol used between websocket-client and websocket-server ?

**Comment by dmonad** [comment]
Sorry, there is no specific documentation for the websockets connector.. You have to check out the code.

If you are going this route: Nathanaels answer here is super valuable: https://github.com/y-js/yjs/issues/82

**Comment by 0xbaadf00d** [comment]
Thanks for the reference to #82.

Do you plan to document the communication protocol ? Do you have any advice where I can find information (filename, structure, JSON?, ...) ?

**Comment by dmonad** [comment]
The sync process of two clients (or server and client) is at follows:

Both parties send a message "sync step 1" to the other side. "sync step 1" describes the state of the content that the client knows about. E.g. It could know about the characters "AB" (client 1) and "XZ" (client 2). 

```
client1 sends "sync step 1" (I know about AB) to client 2
client2 sends "sync step 2" (I know about XZ) to client 1
```

If a client receives "sync step 1" it replies with the missing characters (of course there is more going on..). So client 1 replies with "sync step 2" and all characters that client 2 does not know about.

```
client1 replies with "sync step 2" (insert characters AB at pos x) to client 2
client2 replies with "sync step 2" (insert characters XZ at pos y) to client 1
```

From know on all clients send a "update" message when a change on the document happens.

You should be able to inspect this process in the debugger. In Yjs v12 the above process is simply JSON encoded. In v13 all the messages are binary encoded. But Yjs logs the message content if you set `localstorage.debug = 'y*'` in the browser, or `DEBUG="y*" node src/server.js` in the server.
