### ISSUE TITLE
Event that fires when all updates are received by the server

### ISSUE THREAD

**Issue by dmonad** [y-js/yjs#102]
There should be a way to get notified when all changes are successfully received (and computed) by the server / other clients.

I propose that there would be an object the y instance that describes the sync state:

```js
y.state = 'offline' || 'connecting' || 'synced' || 'update pending'
```

Also it should be possible to listen to changes on the sync state:
```js
y.on('stateChange', function (y, state) {
  console.log(state)
})
```

**Comment by calibr** [comment]
Hello @dmonad, just curious about this feature:

- What does "server" mean here? As far as I know Yjs is decentralized library(in general, I don't take into account specific cases like websocket client/server)
- Does `state` become `synced` if all connected peers have passed the synchronization step with current peer?

**Comment by dmonad** [comment]
> What does "server" mean here? As far as I know Yjs is decentralized library(in general, I don't take into account specific cases like websocket client/server)

Of course, all concepts should work with any connector topology. This will also work when decentralized.

> Does state become synced if all connected peers have passed the synchronization step with current peer?

This would be up to the connector. But I think this approach makes a lot of sense. This is how I would implement it in y-webrtc.

**Comment by calibr** [comment]
@dmonad thanks for the explanation

**Comment by NeoLegends** [comment]
@dmonad How about returning promises from the y data types that resolve once the respective data is synced instead of a global event? Would surely make working with yjs nicer.

**Comment by dmonad** [comment]
I like that idea. So you basically want to get a confirmation when the type synced. This makes sense because you don't want to show a pending icon when the cursor location changes (or other unrelated data)

**Comment by NeoLegends** [comment]
Yeah like:

`y.share.myYMap.set('key', 'value').then(...)`

or `await y.share.myYMap.set('key', 'value');`.

**Comment by dmonad** [comment]
My use-case would be to show an icon that confirms that the server received the changes. My remark in your promise approach is that it does not work for bindings. I think that my state approach (but each type) would be easier to use in my scenario. We also need an event that fires on the type when the state changes.

**Comment by NeoLegends** [comment]
Indeed, the promise approach does not cover bindings. These two features are orthogonal to each other, I guess. The global event could cover bindings and imperative usage while the promises would only be used for imperative usage of yjs.

**Comment by dmonad** [comment]
I see that there are some use-cases for the Promise approach. But I'd need to return a Promise for every method that changes the type - and I don't want to do that. E.g. `yMap.set` current returns the set value, and I don't want to change that.

Here is what I'm currently thinking about implementing:
Each type will have a `state` object that contains information if its content (and its children) are synced to the server. You will also be able to listen for changes on the state object:

```js
ymap.state.status = 'offline' || 'connecting' || 'synced' || 'update pending'
ymap.state.once('status-change', function () {
  // ymap.status.status changed..
})
```

You will also be able to do the imperative approach with a little trick:

```js
ymap.set('key', 'value')
await new Promise(resolve => ymap.state.once('synced', resolve))
```
