### ISSUE TITLE
yRichtext for yjs v13 HTML input

### ISSUE THREAD

**Issue by boschDev** [y-js/yjs#103]
When testing your quill example and pasting a random news article (https://nos.nl/artikel/2219686-moeder-ontvoerde-baby-hannah-uit-frustratie.html) for the styling. I found out that the styling also will be visable in quill but the text will not be shared. Also when I apply the text styling my self Yjs will stop sharing the content. The text sharing will after this not work util I refresh the page.

**Comment by dmonad** [comment]
Your node server does not use the same Yjs version as the client. Please link the yjs repository to y-websockets-server:

```sh
cd y-websockets-server/node_modules
ln -s ~/path/to/yjs
```

**Comment by boschDev** [comment]
I just found the error. When i change rule number 5 in the `server.js` file from
```
const Y = require('../../yjs/y.node.js')
```
to
```
const Y = require('yjs')
```
will fix the error.

**Comment by dmonad** [comment]
Whoops.. That's right. good job!
