### ISSUE TITLE
Richtext Yjs v13 Changing the font heading not syncing

### ISSUE THREAD

**Issue by boschDev** [y-js/yjs#104]
If you have the rich-text example app on 2 different windows open in window1 change the font size and window2 begins with typing. You will see that te styling only will be visible on windows 1 and not on window2.
![screenshot from 2018-02-27 17-29-14](https://user-images.githubusercontent.com/11442533/36740987-4854f966-1be4-11e8-8cf6-1ef9671ee3d6.png)

**Comment by dmonad** [comment]
Did you link the Yjs directory to y-websockets-server/node_modules?

**Comment by dmonad** [comment]
Because this works for me. Otherwise I need more steps to reproduce..

**Comment by boschDev** [comment]
I have linked the yjs dir to y-websockets-server/node_modules
```

**Comment by dmonad** [comment]
Okay got it. This issue happens when creating a block-format (heading, list, code) in the last line.

Thanks for reporting. I will attend this issue tonight!
