### ISSUE TITLE
Yjs V13 removing items from Y-array

### ISSUE THREAD

**Issue by emreeren** [y-js/yjs#107]
Hello, thank you very much for creating this project. I learned a lot of great stuff here.

I built a small test app based on chat example and it removes old messages as the example does. However on debug logs I can see removed messages keeps syncing between new clients even they don't exists in Y-array anymore. I think this is needed to ensure all clients always gets the updates however I feel like I'll probably need to do something to prevent that historical data to grow a lot. I saw some flush methods in test helper lib but before digging it deeper I'll be glad to know if it is something I should care about or not :)

**Comment by dmonad** [comment]
It is true that deleted data is synced for some time. This is necessary for the syncing algorithm to work. But eventually the data is going to be garbage collected.

Well.. there are some GC bugs in the current version. I'm currently reworking the GC approach. 
But in gene this is not something you should care about ;)

**Comment by emreeren** [comment]
fyi: I released a point of sale project that uses "revolutionary" y-js 13 to allow communication between terminals. https://github.com/emreeren/pmpos3. Works great!

**Comment by dmonad** [comment]
looks promising :grin:
