### ISSUE TITLE
Incompatible with create-react-app because minify fails

### ISSUE THREAD

**Issue by moppymopperson** [y-js/yjs#108]
If you create a react project and include the following, running `npm run build` will fail at several places in `y.js` because it can't successfully minify the code.

I tried some hacky solutions, but I wasn't able to fix it by just changing a few lines.

```
import Y from 'yjs'
import yWebsocketsClient from 'y-websockets-client'
import yMemory from 'y-memory'
import yArray from 'y-array'
import yText from 'y-text'
import yMap from 'y-map'
Y.extend(yMap, yArray, yText, yWebsocketsClient, yMemory)
```

**Comment by moppymopperson** [comment]
I've been trying to fix this, but I don't understand Gulp or how it is compiling so I've been unable to pinpoint the issue.

**Comment by er06645810** [comment]
For anybody else who stumbles across this, you can get around it by importing the version of the file in the dist folder using its file path. For example 

```
import Y from 'node_modules/yjs/dist/y.js'
```

**Comment by moppymopperson** [comment]
For anybody else who stumbles across this, you can get around it by importing the version of the file in the dist folder using its file path. For example 

```
import Y from 'node_modules/yjs/dist/y.js'
```

**Comment by dmonad** [comment]
Thanks for the info @moppymopperson! 

This works in the current beta, so I'll close this issue

**Comment by moppymopperson** [comment]
Glad to hear it! Where can I snag the beta version?

**Comment by universalsequences** [comment]
I'm also stuck trying to get yjs to work with react. When installing yjs via yarn, there is no "dist" folder. Similarly, the github repo has no "dist" folder. Anyone know how to get the package with the y.js file? 

I'd love to use this amazing library, it's got me excited, but I can't quite figure this out.
