### ISSUE TITLE
Critical dependency warning

### ISSUE THREAD

**Issue by Thyoity** [y-js/yjs#113]
When I start my client-side with yjs, its giving me this warning in the console:

![image](https://user-images.githubusercontent.com/10885945/39329618-49bc8f4e-4975-11e8-9c4c-3a32854add7b.png)

Everything is working fine, but this warning is bothering me a bit. Is this warning a known issue? It happens when I initialize Y, possibly when I'm importing from 'yjs' package. Like this:

```
import Y from 'yjs'
//... other imports

Y.extend(yArray, yWebsocketsClient, yMemory, yMap, yText)
```

**Comment by dmonad** [comment]
Hey @Thyoity, are you using a module bundler?

**Comment by Thyoity** [comment]
Yes, I'm using Webpack.

**Comment by nantoniazzi** [comment]
I have the same problem with webpack too
