### ISSUE TITLE
CRDT algorithm

### ISSUE THREAD

**Issue by aral** [y-js/yjs#115]
First off, thank you for making and sharing y.js :)

I tried to find some information on the CRDT algorithm you’re using but couldn’t (apologies if I missed something). 

In the draft of a paper I could find online, it mentioned that the algorithm is similar to WOOT but there were no further details.

I’ve recently been looking into logoot and also LSEQ (which I’m playing with at the moment and it looks very promising).

The reason I’m asking is because, regardless of the system I choose to go with I will have to extend it to include signed operations as well as permissioned operations (by including a list of authorised public keys within the signed operations) and so I do need to grok the algorithm involved.

Thanks again :)

**Comment by emreeren** [comment]
> In the draft of a paper I could find online, it 

Hello Aral. Are you referring to this paper? https://github.com/y-js/yjs/issues/99#issuecomment-368078505

**Comment by aral** [comment]
Hey Emre,

That’s the one! Teşekkürler :)

Aral

**Comment by dmonad** [comment]
Thanks for replying @emreeren
