### ISSUE TITLE
YMap: add eventlistener before sync

### ISSUE THREAD

**Issue by druuu** [y-js/yjs#119]
```
let y = new Y('editor', {
    connector: {
        name: 'webrtc',
        room: 'room'
    }
}
var ymap = y.define('ymap', Y.Map);
ymap.observe(function (e) {
    console.log('event fired..');
});
```
sync starts before 'observe' event listener is attached. Can we attach event listener before syncing starts.

**Comment by dmonad** [comment]
Sync is always an asynchronous process. The event handler should always be attached before any data comes in. Or am I missing something?
