### ISSUE TITLE
"Please report this"

### ISSUE THREAD

**Issue by Joeao** [y-js/yjs#120]
Got an error saying "This should not happen .. :( please report this" x4

Was carrying out some unrealistic collaborative testing on a Quill element using insertText and insertEmbed functions. Reporting as I was told to.

"quill": "1.3.6",
"y-array": "10.1.4",
"y-map": "10.1.2",
"y-memory": "8.0.9",
"y-richtext": "^9.0.8",
"y-websockets-client": "8.0.16",
"yjs": "12.3.3"

**Comment by dmonad** [comment]
Thanks Joe, you are a good lad :p 

Maybe I should actually report what is happening in the error messages.. Will close because I don't know what to do with it :sweat_smile:
