### ISSUE TITLE
Readme: wrong CDN link?

### ISSUE THREAD

**Issue by adabru** [y-js/yjs#121]
Hi @dmonad, are you doing well?

For the issue: In this repo's Readme, the displayed CDN link `<script src="https://cdn.jsdelivr.net/npm/yjs@12/src/y.js"></script>` gives me errors. I guess it should be `<script src="https://cdn.jsdelivr.net/npm/yjs@12/dist/y.js"></script>`.

I am using your framework now to develop a collaborative requirements-management tool. 

I enjoy the framework's api very much, but the documentation is still very lacking in my opinion. I miss a doc-search and an extensive use case collection with explanations, performance considerations, security issues, bla bla. Can't they engage a HiWi at i5 with such task?? I'd guess the online guidance is rather hard for people not knowing the framework from word-of-mouth :/

**Comment by dmonad** [comment]
Hey, I always welcome new contributors :-) 

The framework is now solely maintained by me..

Thanks for reporting this. I already updated the docs.
