### ISSUE TITLE
tutorial of y-richtext

### ISSUE THREAD

**Issue by cwwei** [y-js/yjs#127]
I am running the examples introduced in Y-richtext

But I got some errors.
![capture](https://user-images.githubusercontent.com/12724280/48668973-43049280-eb34-11e8-8115-497c4ea424b3.JPG)

My app.js file looked like this,
-------------------------------------------------------
require('y-websockets-client')(Y)
require('y-memory')(Y)
require('y-map')(Y)
require('y-text')(Y)

Y({
  db: {
    name: 'memory'
  },
  connector: {
    name: 'websockets-client',
    room: 'richtext-example'
  },
  share: {
    richtext: 'Richtext' // y.share.richtext is of type Y.Richtext
  }
}).then(function (y) {
  window.yquill = y

  // create quill element
  window.quill = new Quill('#editor', {
    modules: {
      'toolbar': { container: '#toolbar' },
      'link-tooltip': true
    },
    theme: 'snow'
  })
  // bind quill to richtext type
  y.share.richtext.bindQuill(window.quill)
})     
---------------------------------------------------------

Any help?

**Comment by dmonad** [comment]
Hey, I'm currently refactoring. My current focus is on the Prosemirror binding. But I will get back to Quill after that.

**Comment by dmonad** [comment]
Hey, you can check out the new example section now.

https://yjs.website/tutorial-quill.html or the new examples folder
