### ISSUE TITLE
how can't get the browser version?

### ISSUE THREAD

**Issue by mccoysc** [y-js/yjs#128]
in chrome(version 69)

`<script src="https://cdn.jsdelivr.net/npm/yjs@12/src/y.js"></script>
<script src="https://cdn.jsdelivr.net/npm/y-array@10/dist/y-array.js"></script>
<script src="https://cdn.jsdelivr.net/npm/y-websockets-client@8/dist/y-websockets-client.js"></script>
<script src="https://cdn.jsdelivr.net/npm/y-memory@8/dist/y-memory.js"></script>
<script src="https://cdn.jsdelivr.net/npm/y-map@10/dist/y-map.js"></script>
<script src="https://cdn.jsdelivr.net/npm/y-text@9/dist/y-text.js"></script>`

this code include would cause an error:

Uncaught ReferenceError: require is not defined
    at y.js:4
(anonymous) @ y.js:4
Array.js:5 Uncaught TypeError: Cannot read property 'CustomType' of undefined
    at a (Array.js:5)
    at Object.1 (Array.js:354)
    at i (_prelude.js:1)
    at e (_prelude.js:1)
    at _prelude.js:1
    at _prelude.js:1
    at _prelude.js:1
a @ Array.js:5
1 @ Array.js:354
i @ _prelude.js:1
e @ _prelude.js:1
(anonymous) @ _prelude.js:1
(anonymous) @ _prelude.js:1
(anonymous) @ _prelude.js:1
Websockets-client.js:2 Uncaught TypeError: Super expression must either be null or a function, not undefined
    at i (Websockets-client.js:2)
    at Websockets-client.js:14
    at s (Websockets-client.js:14)
    at Object.<anonymous> (Websockets-client.js:111)
    at Object.46.socket.io-client (Websockets-client.js:111)
    at o (_prelude.js:1)
    at t (_prelude.js:1)
    at _prelude.js:1
    at _prelude.js:1
    at _prelude.js:1
i @ Websockets-client.js:2
(anonymous) @ Websockets-client.js:14
s @ Websockets-client.js:14
(anonymous) @ Websockets-client.js:111
46.socket.io-client @ Websockets-client.js:111
o @ _prelude.js:1
t @ _prelude.js:1
(anonymous) @ _prelude.js:1
(anonymous) @ _prelude.js:1
(anonymous) @ _prelude.js:1
RedBlackTree.js:6 Uncaught ReferenceError: regeneratorRuntime is not defined
    at RedBlackTree.js:6
    at t.exports (RedBlackTree.js:6)
    at l (Memory.js:5)
    at Object.1../RedBlackTree.js (Memory.js:71)
    at i (_prelude.js:1)
    at e (_prelude.js:1)
    at _prelude.js:1
    at _prelude.js:1
    at _prelude.js:1
(anonymous) @ RedBlackTree.js:6
t.exports @ RedBlackTree.js:6
l @ Memory.js:5
1../RedBlackTree.js @ Memory.js:71
i @ _prelude.js:1
e @ _prelude.js:1
(anonymous) @ _prelude.js:1
(anonymous) @ _prelude.js:1
(anonymous) @ _prelude.js:1
Map.js:5 Uncaught TypeError: Cannot read property 'CustomType' of undefined
    at s (Map.js:5)
    at Object.1 (Map.js:329)
    at o (_prelude.js:1)
    at e (_prelude.js:1)
    at _prelude.js:1
    at _prelude.js:1
    at _prelude.js:1
s @ Map.js:5
1 @ Map.js:329
o @ _prelude.js:1
e @ _prelude.js:1
(anonymous) @ _prelude.js:1
(anonymous) @ _prelude.js:1
(anonymous) @ _prelude.js:1
Text.js:8 Uncaught TypeError: e.requestModules is not a function
    at s (Text.js:8)
    at Object.2.fast-diff (Text.js:577)
    at i (_prelude.js:1)
    at e (_prelude.js:1)
    at _prelude.js:1
    at _prelude.js:1
    at _prelude.js:1

**Comment by mccoysc** [comment]
@dmonad

**Comment by dmonad** [comment]
Try `https://cdn.jsdelivr.net/npm/yjs@12/dist/y.js` instead of `https://cdn.jsdelivr.net/npm/yjs@12/src/y.js`.

Thanks for reporting this. I'll update the docs
