### ISSUE TITLE
js-ipfs version 0.33.00 + not work

### ISSUE THREAD

**Issue by mccoysc** [y-js/yjs#129]
js-ipfs 0.33.0 and above do not work well with yjs "y-ipfs-connector".
i found that after yjs init ok,the "await ipfs.pubsub.ls()" would list an empty topic array....this is not in normal state....it means "y-ipfs-connector" subscribe nothing from ipfs, so it will receive nothing from ipfs

**Comment by dmonad** [comment]
Hey, can you report this issue to the creators of the connector?

https://github.com/ipfs-shipyard/y-ipfs-connector
