### ISSUE TITLE
y-js.org make browser hang up

### ISSUE THREAD

**Issue by mccoysc** [y-js/yjs#132]
when open y-js.org using chrome,firefox and so on, the browser would be hang up and dead always

**Comment by mccoysc** [comment]
@dmonad

**Comment by dmonad** [comment]
Sorry about that @mccoysc 

There are some people posting huge amounts of content into the examples.

In the next few days I'll publish a new website that is better protected. You can have a look: https://yjs.website

**Comment by dmonad** [comment]
y-js.org works again now.
