### ISSUE TITLE
y-websockets-client can't work with y.js of version 13.x.x

### ISSUE THREAD

**Issue by mccoysc** [y-js/yjs#133]
y-websockets-client can't work with y.js of version 13.x.x

**Comment by Joeao** [comment]
You shouldn't make duplicate issues for the same problem.

**Comment by dmonad** [comment]
v13 is still in beta and is incompatible with v12.

If you'd like to run the websockets server, you can do so by calling `node --experimental-modules yjs/provider/websocket/server.js`.

Have a look at the new example section to get started.
