### ISSUE TITLE
need add db or connector or share  dynamically

### ISSUE THREAD

**Issue by mccoysc** [y-js/yjs#135]
for example:
now all db,connector and share should be made when Y().then(...),
it can't be add  dynamically.
if i make a dapp like twiter:
a feed can be added in an array,but to the comments, i need a new array which added dynamically .
now yjs have no  this feature.

**Comment by mccoysc** [comment]
@dmonad

**Comment by dmonad** [comment]
Hi @mccoysc , since this is not a bug-report, I kindly ask you to ask your question in the chat.

https://gitter.im/y-js/yjs
