### ISSUE TITLE
Cannot set property 'RbTree' of undefined

### ISSUE THREAD

**Issue by mtn** [y-js/yjs#141]
Sorry if this is the wrong place to open this. At the moment, I'm not sure if this is an issue originating in this repository, `y-memory`, or something I'm doing wrong. I have the following setup:

```js
Y({
  db: {
    name: "memory",
  },
  connector: {
    name: "ipfs",
    room: "ipfs-yjs-test",
    ipfs: ipfs,
  },
  share: {
    "textfield": "Text"
  }
}).then((y) => {
  y.share.textfield.bind(document.getElementById("textfield"));
});
```

A link to the full file: https://gist.githubusercontent.com/mtn/6be2e1a24be476bbd22f9defa1061c51/raw/c38e1efe8be7381951b8c7d879a33182c47382d3/app.js

I'm basically fully following the steps outlined by this video: https://www.youtube.com/watch?v=-kdx8rJd8rQ

I get the following error:
<img width="771" alt="screen shot 2019-02-23 at 8 15 14 am" src="https://user-images.githubusercontent.com/4515110/53287530-123f8500-3743-11e9-950d-52694c1fcb34.png">

Is this a bug, or am I just doing something wrong?

**Comment by mtn** [comment]
Closing, I see that the minimal example from the README basically works, so some API or dependency probably just changed.

**Comment by peterhuba** [comment]
By any chance do you remember how could you fix this? Facing a similar issue.

**Comment by mtn** [comment]
@peterhuba Does the minimal example not work? Sorry, haven't worked with this code in a few months.

**Comment by harrybutt** [comment]
@peterhuba @mtn did you manage to figure this out? currently experiencing the same problems but npm installs of all the yjs packages seems to be working fine

**Comment by jylopez** [comment]
Are you using v13? I had the same problem, then switched to v12 and it worked. 

I guess you can't do things like `require('y-memory')(Y)` in v13.

**Comment by whatsdis** [comment]
this needs to be addressed as it is a blocker. i followed the direction on the website but i got this error.
