### ISSUE TITLE
Project homepage does not define CRDT

### ISSUE THREAD

**Issue by pimlottc-gov** [y-js/yjs#146]
Hi there, I just landed on this page from another project that was mentioned in a forum. Not knowing anything about it, I was confused by the projects short description:

> A CRDT library with a powerful abstraction of shared data http://y-js.org

"CRDT" is not mentioned anywhere in README.me.  It would be useful to have a some sort of explanation for new users not familiar with this problem space.  Thanks!

**Comment by dmonad** [comment]
Thanks, that's a very helpful comment. I'll add a basic into to CRDTs and automatic conflict resolution to the README.

**Comment by dmonad** [comment]
I added a description of CRDTs and the CRDT used in Yjs in the v13 docs.

https://github.com/y-js/yjs/blob/master/README.v13.md#Yjs-CRDT-Algorithm
