### ISSUE TITLE
AceBinding in v13

### ISSUE THREAD

**Issue by Rush** [y-js/yjs#147]
Hi there - congrats on the recent refactor! I just discovered `yjs` and found it slightly confusing that I should actually open https://github.com/y-js/yjs/blob/master/README.v13.md in order to use it rather than the regular README. In my use case I'm interested in the Ace editor binding. Is there one completed for v13? Even if in beta.

Or would you rather advise me trying out v12 instead?

**Comment by dmonad** [comment]
The Ace binding only works for v12. But I plan to support Ace too in v13. If it makes no difference to you, you could try out the CodeMirror binding (a similar editor) that even supports cursors.

**Comment by Rush** [comment]
@dmonad actually I already have a lot of stuff built around Ace so I would prefer to stick to it.

**Comment by Rush** [comment]
@dmonad do you anticipate any issues with building around v12 and then upgrading to v13 once it's ready?

**Comment by dmonad** [comment]
If you are just using the text binding and pure y-websockets-client/server - the upgrade will be pretty easy. There are similar packages for v13.

**Comment by Rush** [comment]
Thanks. I will use v12 for the time being. btw. Ace does seem to support collaborative features through an extension https://github.com/convergencelabs/ace-collab-ext

**Comment by dmonad** [comment]
Thanks, that's a good resource. I didn't even know there was a cursor module. I will add cursors support for Ace too when I reimplement the editor binding.

**Comment by chaosprint** [comment]
Hi, @dmonad I am wondering why ace binding is no longer available?
