### ISSUE TITLE
webpack compile error

### ISSUE THREAD

**Issue by chenkovsky** [y-js/yjs#148]
It complains 'Attempted to assign to readonly property.', at:

```
module.exports = extend;
```

**Comment by chenkovsky** [comment]
maybe I should submit issue on y-text project. it seems that y-text is useless now? we only need to include yjs project? If that's true, document should be updated.

**Comment by dmonad** [comment]
I figure you are using the master branch. The master branch is the working release v13 - it is documented in the dedicated v13 docs https://github.com/y-js/yjs/blob/master/README.v13.md

You are right that y-text is not needed anymore. The Y.Text type is now part of Yjs.

I agree that we need an upgrade guide to v13.
