### ISSUE TITLE
use single undoManager for multiple types

### ISSUE THREAD

**Issue by calibr** [y-js/yjs#156]
I'm glad to see new implentation of UndoManager, it is much cleaner!

For my task I need something like this:

```
new UndoManager([ type1, type2 ])
```

to have the same stack for both type1 and type2, so their changes can be captured together with the same StackItems. I tried to set separate observers for the types, but the problem is when I do undo and the undoying StackItem has changes in both types it creates two StackItems for the redo stack(UndoManager do not capture items together for undo/redo). I also tried using the afterTransaction event to listen to changes instead of using observeDeep, but result was the same, because afterTransaction also was being called twice for undo.

@dmonad do you have any ideas on how to implement this?

**Comment by dmonad** [comment]
You are right about this. I implemented your suggestion. Now it either accepts a single type as argument, or an array of types (as you suggested).

**Comment by calibr** [comment]
@dmonad wow! thank you!
