### ISSUE TITLE
Input y-text binding

### ISSUE THREAD

**Issue by boschDev** [y-js/yjs#160]
Well done with developing the new version. Now I saw that you were putting all bindings on separate repos. I only miss the html input binding. Does this come together in the [y-js/y-textarea](https://github.com/y-js/y-textarea) or will there be a separate repo for that.

**Comment by dmonad** [comment]
Thanks @boschDev The bindings will be in separate repositories.  The reason is that some bindings now have dependencies and I don't want to blow up a single repository. Though I have to say that the monorepo approach was much easier to handle.
