### ISSUE TITLE
how do i build a connector?

### ISSUE THREAD

**Issue by crapthings** [y-js/yjs#163]
i want to build a connector with deepstream, and add quill-cursors support, so when its editing in richtext, user can see where others cursor at.

is there a guide?

**Comment by dmonad** [comment]
Hey @crapthings, for v12 the best place to start is the source code. For v13, there is a simple explanation of how document updates work: https://github.com/y-js/yjs/blob/master/README.v13.md#Document-Updates

Note that v12 will soon be put out of commission. Most editor bindings for v13 already support cursors. [Check this out](https://yjs-demos.now.sh/quill/) :wink:
