### ISSUE TITLE
TypeError in custom connector.

### ISSUE THREAD

**Issue by cphyc** [y-js/yjs#21]
There seems to be an error in custom connector.
In https://github.com/y-js/yjs/blob/master/lib/ConnectorClass.coffee#L113, you're pushing an array to @compute_when_synced whereas in https://github.com/y-js/yjs/blob/master/lib/ConnectorClass.coffee#L195 you expect a function !

I'm filling a PR for that.

**Comment by DadaMonad** [comment]
fixed by @cphyc
