### ISSUE TITLE
Did I miss something in the tutorial?

### ISSUE THREAD

**Issue by kay-is** [y-js/yjs#31]
I don't quite understand how yjs works.

I have the following code, that I run in the browser:

    import Y from 'yjs'
    import 'y-xmpp/y-xmpp'

    const connector = new Y.XMPP({}).join('some-test-room-123546')
    const y = new Y(connector) // till here everything works fine

    const text = y.val('text')

    if(text) console.log(text) // should happen on every other client
    else y.val('text', 'some text') // should only happen on the first client

My idea was, if I use a connector that joins the same room on every client, the `'text'` value would be synced across all connected clients. So on the first time `text` is `null` and the value gets created and if I open the second browser window, the value gets logged.

But somehow it *always* gets created. Like it was never synced with the new client.

**Comment by DadaMonad** [comment]
Hi kay,

I understand that this is a bit confusing, but this is the expected behavior. When the user joins the room for the first time, it does not know yet that there is already content. You can wait until the user is synced with the other users in the room.

```
connector.whenSynced(function(){console.log("synchronized, the 'text' property should exist now")})
```

**Comment by kay-is** [comment]
Ah okay, thank you. So it's like with the `onload` for DOM operations.

What I found was, that `whenSynced` is only fired when at least 2 users are connected.

I can only check if a property already exists if the system is synced, but I have to wait for `whenSynced` to do this, which only fires when the second user comes. How do I create a new property only if no other user has already created it?

**Comment by DadaMonad** [comment]
You basically let both of your clients create the value concurrently. But when they are synced, only one of them will prevail. For each client you could observe if its value was overwritten by another client.

In the tutorial is a section "Handling Concurrency" wich explains this case in more detail.

But I realize that this is a bit confusing. In the next version of Yjs I'll offer some functionality to handle this more elegantly.
