### ISSUE TITLE
real world (xmpp-) applications

### ISSUE THREAD

**Issue by flosse** [y-js/yjs#39]
Are there any known applications (like etherpad) that use Yjs and xmpp?
If not, what would be the hardest part to build a etherpad clone?

**Comment by DadaMonad** [comment]
I built a [richtext type](https://github.com/y-js/y-richtext.git) for Yjs, that you could bind to [QuillJs](http://quilljs.com/). However, it is not yet available in the newest version of Yjs (I'm currently working on it). It supported cursors, images, and, of course, selections (e.g. make a selected text bold).

It would be rather easy to highlight text by creator.

I'll leave this issue open until I implemented it.

**Comment by flosse** [comment]
> I built a richtext type for Yjs, that you could bind to QuillJs. 

That sounds very interesting! What would be the concrete steps required to make this real?

**Comment by DadaMonad** [comment]
Well, it supported all of the features of QuillJs. If you need more features, I could answer you how to implement them (or maybe I will). In a few weeks the Richtext type will be available again. Then you just do:

```
var quill = new Quill(..)
y.share.richtext.bind(quill)
```

And here you go - you have a collaborative richtext editor. I'm unsure if I understood your question correctly.

**Comment by DadaMonad** [comment]
As promised the Richtext type is ready. There is a documented example on the website. Let me know if you have feature requests.
