### ISSUE TITLE
Migration status?

### ISSUE THREAD

**Issue by jbruni** [y-js/yjs#41]
There is a NOTE in the readme: 

```
This project is currently migrating. So there may exist some information that is not true anymore.
```

I want to use Yjs. What is the status of this migration? What should I be careful with if I start using Yjs right now?

Thank you.

**Comment by nicolaescu** [comment]
Hello,

We have been releasing a new version of the library, which is now stable. We are still updating the documentation and of course development continues, but you can use the latest version right now.

**Comment by DadaMonad** [comment]
@jbruni 

As @nicolaescu said, Yjs is pretty stable right now. But I'm still working on the docs. This comment is mostly related to the github wiki (which still contains some old information). Everything is on our [website](y-js.org) is up to date.

Don't be afraid to drop a line via [gitter](https://gitter.im/y-js/yjs?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge) if you run into troubles.
