### ISSUE TITLE
Destroy a Yjs instance

### ISSUE THREAD

**Issue by DadaMonad** [y-js/yjs#42]
The `.destroy()` method is not correctly implemented. It should destroy the database, and cleanup all bindings.

Therefore, the types also must implement a `destroy()` method.

**Comment by dennislaupman** [comment]
Or recreating room's to provide to much (unnecessary rooms)

**Comment by DadaMonad** [comment]
I'm unsure what exactly you want to do. If you want to (temporarily) close the connection, you can call `y.connector.disconnect()` on all of our connectors. `y.connector.reconnect()` will automatically reconnect. But note: There is a bunch of information that needs to be synced every time you reconnect. It was initially meant for connection loss. If it is unlikely that the client reconnects to a room, you can also use `y.destroy()`, and create a new yjs instance, when the clients needs the data again (when this issue is fixed of course)

**Comment by DadaMonad** [comment]
Every type has unbind features now. `y.destroy()` is also implemented correctly now (including automatic unbind of listeners, and cleanup). Note that you will get weird error messages when you destroy an instance and still try to use it.
