### ISSUE TITLE
Yjs distribution

### ISSUE THREAD

**Issue by DadaMonad** [y-js/yjs#44]
Create a Yjs distribution.

One approach would be to create another project that references to y-* repositories that are know to work together (e.g. via bower).

I'm unsure if this is a good idea (this would be one more package to maintain :(

**Comment by istvank** [comment]
Is this a potential solution for the issue that I told you, about breaking Yjs almost everytime I do `bower update`? What I was refering to is some kind of combination of y-* modules that are guaranteed to work together. It could be a yjs-package#~0.8.0 bower package (possibly including a test kit) that itself refers to y-* modules in the highest possible ~ version.

What adds to the confusion is that currently, yjs runs on 0.8.x while all the other modules are stuck on 0.7.x. For example, how do I know, if 0.8.x of yjs works together with the 0.7.x modules? Because the 0.6.x version of yjs certainly doesn't work together with the 0.5.x versions.

Hope I made it clear enough. :)

**Comment by nicolaescu** [comment]
Hi,
Thanks for sharing this!
We will fix it as soon as possible. We should also think about more 
clear versioning names :)

On 13.02.2016 12:52, István Koren wrote:
>
> Is this a potential solution for the issue that I told you, about 
> breaking Yjs almost everytime I do |bower update|? What I was refering 
> to is some kind of combination of y-* modules that are guaranteed to 
> work together. It could be a yjs-package#~0.8.0 bower package 
> (possibly including a test kit) that itself refers to y-* modules in 
> the highest possible ~ version.
>
> What adds to the confusion is that currently, yjs runs on 0.8.x while 
> all the other modules are stuck on 0.7.x. For example, how do I know, 
> if 0.8.x of yjs works together with the 0.7.x modules? Because the 
> 0.6.x version of yjs certainly doesn't work together with the 0.5.x 
> versions.
>
> Hope I made it clear enough. :)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/y-js/yjs/issues/44#issuecomment-183651879>.
>

-- 
Petru Nicolaescu, M.Sc.

Advanced Community Information Systems (ACIS)
Chair for Computer Science 5 (Information Systems & Databases)
Room 6239
RWTH Aachen
Ahornstr. 55    52056 Aachen
Germany
Email: nicolaescu@dbis.rwth-aachen.de
Tel:     +49 (0) 241 80 21516

**Comment by istvank** [comment]
Hi, yes, I'm sure that @DadaMonad will soon come up with a good solution.
What exactly do you mean by "versioning names"?

**Comment by nicolaescu** [comment]
Yes, I am also sure.
I mean that we are still in the process of updating all existing 
components and the documentation to work with/fit to the latest Yjs 
release.. so hopefully they will all reflect soon the latest status.

On 13.02.2016 14:10, István Koren wrote:
>
> Hi, yes, I'm sure that @DadaMonad <https://github.com/DadaMonad> will 
> soon come up with a good solution.
> What exactly do you mean by "versioning names"?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/y-js/yjs/issues/44#issuecomment-183662486>.
>

-- 
Petru Nicolaescu, M.Sc.

Advanced Community Information Systems (ACIS)
Chair for Computer Science 5 (Information Systems & Databases)
Room 6239
RWTH Aachen
Ahornstr. 55    52056 Aachen
Germany
Email: nicolaescu@dbis.rwth-aachen.de
Tel:     +49 (0) 241 80 21516

**Comment by DadaMonad** [comment]
This is somehow related to #48. I implemented a feature that forbids clients with incompatible versions to sync. Furthermore, I think it is a better idea to fix the interdependencies between Yjs and its modules (Connectors, Types, ..) with [peerDependencies](https://nodejs.org/en/blog/npm/peer-dependencies/) in npm (they are especially designed for plugin systems), and common dependencies in bower. I'd like to proceed with rolling releases, and I'll now be more careful not to break things for other people when they do `bower update`.

I'll start to define the dependencies of all the packages if the y-js organization

**Comment by DadaMonad** [comment]
If you use bower or npm, you'll get an error if you use incompatible versions. This is solved, as mentioned, with peerDependencies. 

I also fixed the version scheme. From Yjs `0.8.x` -> `8.x.y`.
