### ISSUE TITLE
Version Header

### ISSUE THREAD

**Issue by istvank** [y-js/yjs#48]
Hi, first again thanks for the great work! :bowtie: Now to my issue: On the [y-websockets-server page](https://github.com/y-js/y-websockets-server) you describe that the Yjs version of the Web application and of the y-websockets-server have to be the same:
> You have to make sure that the installed yjs package version matches the yjs version used on the client side!

However, if they are different, I get no error. This is especially confusing as I never know which y-websockets-server the "Demo" server provided by you is currently running on. It would be neat to have some kind of versioning header in the initial connection that would throw an error or at least a log message in the browser, that the Yjs versions on client and server are inconsistent.

Even if I employ my own y-websockets-server, I regularly do "bower update" before releasing the client. This occasionally updates the Yjs version, but not the one on the server.

Do you think some kind of hints would be feasible?

**Comment by DadaMonad** [comment]
This was rather easy to implement & totally makes sense. The update will take place when I upgrade the current default server (in the next two weeks). In order to use this feature, both client (and server) need to implement Yjs > 0.8.28

Thanks for the report!

**Comment by istvank** [comment]
Thank you! :clap:
