### ISSUE TITLE
can't create new room when offline

### ISSUE THREAD

**Issue by lukebarlow** [y-js/yjs#55]
I am trying to get truly offline-first behavior working, using the indexeddb database and either webrtc or websockets-client connector. With both of these connectors everything works fine offline with rooms which were previously created while connected. However, when disconnected from the internet and trying to create a new room with either connector, the Promise from the initial Y setup never resolves.

```
Y({
  db: {
    name: 'indexeddb'
  },
  connector: {
    name: 'websockets-client',
    //name: 'webrtc',
    room:  roomName
  },
  sourceDir: '/bower_components',
  share: {
    state : 'Map'
  },
  types: ['Map', 'Array']
}).then((y) => {
   // this point in the code is never reached while disconnected
})
```

**Comment by DadaMonad** [comment]
Sorry it took so long. The problem was that you can't get a user id if you are not connected (user ids are created by the server). Since there is no other solution for this problem, I opted for generating GUIDs instead of retrieving them from the server (but only when using y-indexeddb).

**Comment by lukebarlow** [comment]
many thanks for the fix. Much appreciated
