### ISSUE TITLE
Puzzle regarding client stating the storage medium

### ISSUE THREAD

**Issue by jfstephe** [y-js/yjs#57]
Hi,
First off, it's great to see a current, maintained and documented collaborative working library! My question is why does the client code state the storage mechanism (in-memory/persisted etc). Surely that's a server side concern?
John

**Comment by dmonad** [comment]
Thanks for your feedback!
Yjs is able to share data peer to peer without a server. Let me give you an example: Multiple clients can communicate via WebRTC (using the y-webrtc connector), and store changes using a persistent database (using the y-indexeddb database adapter). Therefore, it is possible to let clients handle persistence.

But that's really up to you. You can also set up a central server for handling persistence.

**Comment by jfstephe** [comment]
Thanks. I have more of a traditional client-server setup, so I suppose the indexddb storage option for the client and the leveldb for the server. :-)

**Comment by dmonad** [comment]
Unless your app is supposed to work offline you should use y-memory storage on the client side. It is possible to create offline-apps ([codocs](https://codocs.github.io/) is an app that works offline). I'm currently updating the docs for y-indexeddb, so you should stay tuned.
