### ISSUE TITLE
Fill instance with data from node server before clients instance is instantiated

### ISSUE THREAD

**Issue by Feasze** [y-js/yjs#59]
We want to fill an Y room on the (node) server with data before the client's instance is totally instantiated.

some details:
**node server:**
We use the web-sockets connector and an custom database adapter. The database adapter extends the memory database.
The custom database adapter is used to get the data and fill the room.
**the client:**
uses web-sockets connector and memory adapter.

The problem is that we want to have data in the (server) memory BEFORE clients can get the data. To set the data in Y we need to use the transact method in the database adapter, but to use this we need to initialize the whole Y instance. This way the node server responds to the client that Y is ready while setting the data. This creates race conditions and then the client does not get all the data from the server.

**what we like to have is the following:**
client sends to node a request to connect to the room -> node creates a new instance -> database adapter gets the data we want to use to fill the room -> database adapter fills room -> instance is ready on the node server -> node server sends room to client -> client gets the room and the data

at this moment the node server already sends an response to the client after getting the data, but before he can set the data. This is because to set the data he has to use the transact. Which only can be used if the room is ready as far I understand.
![image](https://cloud.githubusercontent.com/assets/23384990/20709490/03eef912-b636-11e6-90bb-795420383945.png)

Is there an good way to do this? Or are we looking at this the wrong way?
We like to know if there is an possibility for this, or an way to make it possible.

**Comment by dmonad** [comment]
I think the best way to handle this is to adapt the *server.js* in [y-websockets-server](https://github.com/y-js/y-websockets-server/). Just copy it to your project, and adapt the way Yjs instances are created [(line 35)](https://github.com/y-js/y-websockets-server/blob/master/src/server.js#L35):

```javascript
function getInstanceOfY (room) {
  if (global.yInstances[room] == null) {
    global.yInstances[room] = new Promise (function (resolve, reject) {
      // create Yjs instance
      var yPromise = Y({
        db: {
          name: options.db,
          dir: 'y-leveldb-databases',
          namespace: room
        },
        connector: {
          name: 'websockets-server',
          room: room,
          io: io,
          debug: !!options.debug
        },
        share: {
          map: 'Map'
        }
      })
      // get data from database (assuming it returns a promise)
      var dbRequest = FeaszePerformsDBRequest(room, ..)
      // wait for both promises to resolve
      Promise.all([yPromise, dbRequest]).then(function ([y, dbContent]) {
        // populate y with db content, e.g.
        y.share.map.set('content', dbContent)
        // When everything is ready, resolve the `global.yInstances[room]` promise
        resolve(y)
        // now users can connect to this Y instance
      })
    })

  }
  return global.yInstances[room]
}
```

(+1 for issue quality)

**Comment by dmonad** [comment]
I hope I was able to help. You can comment here if you want me to re-open this issue

**Comment by Feasze** [comment]
Yes sorry for not letting you know. It works perfectly! Thanks for the help.

**Comment by dmonad** [comment]
Great!
