### ISSUE TITLE
Cursor support?

### ISSUE THREAD

**Issue by c-h-** [y-js/yjs#65]
For the Quill adapter is there any support for showing connected clients' cursors?

**Comment by Joeao** [comment]
The feature isn't built into Quill V1.X yet, you can track the issue: https://github.com/quilljs/quill/issues/918

I was using clients cursor highlighting on the old versions of Quill when it was supported by just sending the position down the socket, worked really well.

**Comment by c-h-** [comment]
Ah ok thanks!
