### ISSUE TITLE
Help needed for react build system

### ISSUE THREAD

**Issue by tianhaoz95** [y-js/yjs#67]
I realized that Yjs works in test environment but can not be built. I got this error from react build system:
`static/js/main.0590c1cb.js from UglifyJs`
`SyntaxError: Unexpected token: name (requireModule) [./~/yjs/src/y.js:66,0]`
I tried installing Yjs globally but it didn't work.
Is there any way to work around this? Thanks!

**Comment by dmonad** [comment]
Unfortunately, I'm unfamiliar with React. I guess you are using the npm yjs package. Uglify can't handle `let x = ..` expressions. So you should [babelify](https://babeljs.io/) the Yjs package first, before uglifying..

**Comment by dmonad** [comment]
I actually know of a group that is using Yjs with React. They are probably using babelify too.

**Comment by tianhaoz95** [comment]
hmmmm that's a good point. I will try to babel before build (it that what you suggested?). Right uglify can't handle let expression. What if I go into the npm package and change it to a local var? Normally this is a really really bad idea, but does it worth a shot?

**Comment by tianhaoz95** [comment]
`
gulp.task('dist:es6', function () {
    return (browserify({
      entries: files.dist,
      debug: true,
      standalone: options.moduleName
    }).bundle()
      .pipe(source(options.targetName))
      .pipe(buffer())
      .pipe($.sourcemaps.init({loadMaps: true}))
      // .pipe($.uglify()) -- generators not yet supported see #448
      .pipe($.rename({
        extname: '.es6'
      }))
      .pipe(header(banner, { pkg: require('./package.json') }))
      .pipe($.sourcemaps.write('.'))
      .pipe(gulp.dest('./dist/')))
  })
`

**Comment by tianhaoz95** [comment]
How can I activate this?

gulp.task('dist:es6', function () {
    return (browserify({
      entries: files.dist,
      debug: true,
      standalone: options.moduleName
    }).bundle()
      .pipe(source(options.targetName))
      .pipe(buffer())
      .pipe($.sourcemaps.init({loadMaps: true}))
      // .pipe($.uglify()) -- generators not yet supported see #448
      .pipe($.rename({
        extname: '.es6'
      }))
      .pipe(header(banner, { pkg: require('./package.json') }))
      .pipe($.sourcemaps.write('.'))
      .pipe(gulp.dest('./dist/')))
  })

**Comment by dmonad** [comment]
Thanks @tianhaoz95 ^^

Changing the let expressions wouldn't fix the problem. There are several other ES2015 features I use, that Uglify can't handle. [Here](https://github.com/mishoo/UglifyJS2/issues/448) is the thread that discusses the problem.

Yes, I meant babel. [babelify](https://github.com/babel/babelify) is the respective babel transformer. You should look up how to include the babel transformer in your build process.

Another solution would be to just download one of the [Yjs releases](https://github.com/y-js/yjs/releases). They already include the built sources. Uglify shouldn't have any problems with them.

You asked how to build Yjs.
* `git clone git@github.com:y-js/yjs.git`
* `cd yjs`
* `npm install`
* `gulp dist:es6` - this will only build the es6 compatible file (uglify can't handle them). Run `gulp dist` instead

**Comment by tianhaoz95** [comment]
Thanks! Downloading release sounds like a good idea. How can I use the release?

**Comment by dmonad** [comment]
Just reference to the ./y.js file. It should work with your module system (npm, global include, requires, ..)

**Comment by tianhaoz95** [comment]
oh yes, it worked. Awesome!

**Comment by tianhaoz95** [comment]
Sorry I though it work...
Now it's really weird in that I included directly in my component using `require('./y-array/y-array.es6')(Y)` but it is still trying to Uglify the build. I couldn't find which config file caused it to do so. Do you have any clue like did anything in the file will cause it to alter the build behavior?

static/js/main.3d2ecf94.js from UglifyJs
SyntaxError: Unexpected token: name (YArray) [./src/Pages/Collaborative/y-array/y-array.es6:12,0]

**Comment by tianhaoz95** [comment]
Also, I can only use the es6 file. When I use y.js. It says that
  7:124    error    'define' is not defined

**Comment by dmonad** [comment]
I don't know anything about your build system.. But as you mentioned the y* files need to be uglifyable. The .es6 file contains es6 (es2015) features that uglify can't handle. Try to fix the the errors that result from using the y.js file.

I don't think that the following errors are thrown because of Yjs:
* `error 'define' is not defined`
* `error 'chrome' is not defined`

`'getRandom' is not defined` can only be thrown when executing the testsuite.

I can't help you any further without the full logs.

**Comment by tianhaoz95** [comment]
I used several plugins and it worked! yea! high five man, this is awesome
