### ISSUE TITLE
Support/functionality to retrieve from database?

### ISSUE THREAD

**Issue by dwangus** [y-js/yjs#69]
I don't see a lot of documentation or comments on how exactly one might interact with the various database connectors available? 

Specifically, the app I'm trying to create essentially uses y-js as a P2P "offline mode" in case the "online mode" to the central server doesn't work, but must transition back to the "online mode" once it detects the server is back up again. I'm having difficulty understanding if I even CAN retrieve the intermediate results my app generated with y-js and then send them to the server when transitioning to the online mode again. 

Is this functionality that exists that I just don't see, or would I have to implement my own way of persisting y-js's changes and retrieving them?

**Comment by dmonad** [comment]
It is a bit unclear to me what you want mean / what you want to achieve. The database adapters just save the shared data. If you choose y-indexeddb, the content will be available event without internet connection. When the Connector (y-websockets-client, y-webrtc, ..) is able reconnect, the data will magically update. There are some methods (see docs) that allow you to observe when you are connected / disconnected from the other users.

**Comment by dwangus** [comment]
Sorry, to clarify -- I know that when an individual user/peer is able to re-connect to the "room" that all the other peers are in, the data (as you said) will "magically sync with the server" such that the peer will receive all the updates it had missed while it was disconnected.

However, what I'm trying to do is transition all the data of this entire group of P2P users to an entirely separate, independent server (so, the most up-to-date data of just one user, since all connected users should have the other users' changes as well). To do that, I'd need to manually retrieve all the persisted data of one user's indexeddb or leveldb and actually move it to this other, independent server. Is there functionality provided by y-js that allows me to just do a single method call to retrieve all the persisted data?

For an idea, let's say that this data is all the shared updates/inserts/changes to a textarea. All the P2P users using y-js are connected and store the most up-to-date version of the textarea document using indexeddb or leveldb -- but how do I retrieve the entire document's HTML in one function call from y-js's database, such that I can send it to an entirely different database? (from within a single peer's code)

**Comment by dmonad** [comment]
So you want to export the internal data model to a third party database. This is how you export & import it:

**Export:**
```js
y.db.requestTransaction(function *() {
  var operations = yield* this.getOperations()
  var deleteSet = yield* this.getDeleteSet()
  
  // Save this JSON Object in your database
  var export = { operations, deleteSet }
})
```

**Import:** 
```js
y.db.requestTransaction(function * () {
  yield* this.applyDeleteSet(export.deleteSet)
  this.store.apply(export.operations)
})
```

If possible, I recommend you to save the data in your own format. I.e. assuming you work on a y-text type, just export the data as a string:

```js
var export = y.share.textarea.toString()
```

I don't provide any methods to export the types in some kind of JSON format, this is something you have to do yourself.

Please note: If the *internal data model export* works reliably depends on many factors. But you should be fine if you turn off garbage collection (this means the size of the shared document will never decrease, even if you delete elements).

##### Turn off garbage collection:
When initializing Yjs, set `gc: false` in the connector part:

```js
Y({
  connector: {
    name: ..
    gc: false,
  }
  ..
})
```

**Comment by dwangus** [comment]
Thank you!!!

**Comment by dmonad** [comment]
Sure, good luck..
