### ISSUE TITLE
Install with browserify

### ISSUE THREAD

**Issue by RationalCoding** [y-js/yjs#70]
I am trying to use Y-JS with Browserify and hitting some issues.

I have `npm install --save`'d all of the modules I am using and the `require`  OK, but Y-JS is still looking for them as bower components, so I am getting 404s.

**Comment by RationalCoding** [comment]
It doesn't seem to affect behaviour. The errors just appear in console.

**Comment by dmonad** [comment]
Do you explicitly include all modules?

```js
var Y = require('yjs')
require('y-array')(Y) // add the y-array type to Yjs
require('y-websockets-client')(Y)
require('y-memory')(Y)
require('y-array')(Y)
require('y-map')(Y)
require('y-text')(Y)
// ..
// do the same for all modules you want to use
```

If you forget a module, Yjs searches for them in *bower_components*

**Comment by RationalCoding** [comment]
I have this:

```javascript
var Y = require('yjs')
var YText = require('y-text')(Y)
require('y-memory')(Y)
require('y-array')(Y) // <-- 
require('y-map')(Y)
require('y-webrtc')(Y)
```

But `y-array` still throws a 404. Maybe because it's being used in other modules?

**Comment by dmonad** [comment]
`y-text` depends on `y-array`. So you have to include it in the right order:

```js
var Y = require('yjs')
require('y-array')(Y)
require('y-memory')(Y)
require('y-text')(Y) // <-- 
require('y-map')(Y)
require('y-webrtc')(Y)
```

I mention this in [y-text](https://github.com/y-js/y-text/). But I don't blame you. It gets easily overlooked ;)

**Comment by RationalCoding** [comment]
That fixed it. Thanks a lot!
