### ISSUE TITLE
NPM install gives error

### ISSUE THREAD

**Issue by dennislaupman** [y-js/yjs#71]
npm ERR! Refusing to install package with name "yjs" under a package
npm ERR! also called "yjs". Did you name your project the same
npm ERR! as the dependency you're installing?

You need to change the (project) name in the package file.

Grtz Dennis

**Comment by dmonad** [comment]
Hi Dennis

Try to rename your package (in package.json). This is probably not a Yjs issue. Otherwise please let me know how to reproduce the issue.

**Comment by dmonad** [comment]
I am going to close this now
