### ISSUE TITLE
Support double length unicode

### ISSUE THREAD

**Issue by icarito** [y-js/yjs#73]
Thanks for writing Yjs! I'm using it for https://github.com/somosazucar/Jappy - a Python web development environment.

Yjs mangles unicode characters such as these:
`pairs = ['🐇','🐈','🐒','🐋','🐎','🐍','🐢','🐝','🐂']`

It would be great if it supported it! I'm using the CodeMirror binding, if it makes a difference. The issue can be observed also on http://y-js.org/ examples.

Thanks.

**Comment by dmonad** [comment]
Fixed in y-text@9.5.0

**Comment by icarito** [comment]
Importing new db dump...
