### ISSUE TITLE
*.es6 files contain commonjs code instead of ES6 export statements

### ISSUE THREAD

**Issue by Corrodize** [y-js/yjs#76]
Is this intended to be or could it be a bug? Because we're looking for the yjs versions which we can use with ecmascript 6 import/export statements

**Comment by dmonad** [comment]
The .es6 files are not babelified. But they are not written as ES modules. I'm sorry that this is misleading, but this is not a bug.

The next Yjs release is actually written as a ES module, but it won't be released soon. So you should find a way to import the current module format.
