### ISSUE TITLE
Yjs + IPFS library and demo

### ISSUE THREAD

**Issue by pgte** [y-js/yjs#77]
Just fresh out of the oven:

* an IPFS connector library for Yjs: https://github.com/ipfs-labs/y-ipfs-connector and
* a video demo of it: https://github.com/ipfs/research-CRDT/issues/7

**Comment by dmonad** [comment]
Hi Pedro,

This is awesome! It even seems to work very reliably. Great Job!
I'm gonna link to it in the available connectors section.

**Comment by pgte** [comment]
Awesome, thank you!
