### ISSUE TITLE
how to create a store

### ISSUE THREAD

**Issue by pgte** [y-js/yjs#78]
I'm trying to create a store for Yjs that is backed by an IPFS store, but I'm struggling to find where to start. I've been looking at the Indexeddb and Memory adapters, but I'm failing to understand what is the interface that should be exposed.

Are there any pointers that could help me getting started?

Thanks so much!

**Comment by dmonad** [comment]
Hey, I can only suggest you have look at y-memory or y-indexeddb. You basically have to implement all of their methods. Implementing a db adapter is very tidious at the moment. I plan to change her data is stored persistently - so you may wanna wait for a month. If you want I can send you an example with the new implementation (expect 4 weeks)

**Comment by pgte** [comment]
@dmonad Awesome! Thank you, I think I'll wait 👍

**Comment by NathanaelA** [comment]
@dmonad - Kevin, any news on an upgraded memory stores; or should I just attempt to copy those memory stores functions?

**Comment by dmonad** [comment]
Hey Nathan, great to see that you still are interested in the project!
I implemented a new persistence layer that is more performant than the database adapter. For comparison: a database adapter stores every granular information in the database. Usually each edit is saved in a different database entry. This concept is unfortunately quite expensive when the document grows over time. N database rows are accessed when the document is sent to remote clients, where n is the size of the document. This approach has a few advantages, but I found that this approach does not work well enough for large documents. I have been reworking Yjs for the past few months. It does now support a very efficient binary serialization `y.db.toBinary()`. The idea is to store the serialization in regular intervals to the database. You may also store granular updates to the database in shorter intervals. You can check out the master branches and test it out yourself. y-redis and y-indexeddb support the new persistence approach. 

```js
Y({
  ..
  persistence: {
    name: 'redis'
  }
})
```
.
