### ISSUE TITLE
node that can only follow

### ISSUE THREAD

**Issue by pgte** [y-js/yjs#79]
I need to have a node that is only the follower and that does not have write permissions.
This node should only integrate the changes from the other nodes and never produce changes.
At the protocol level I'm using a private/public key pair to secure this. Whoever has the private key can write, and whoever has the public key can follow.

I implement this at the protocol level (inside a specific connector I'm building) by appending a signature to the messages. When received, this signature can be validated by whoever has the public key.

The problem is, that it looks like the protocol requires all nodes to be able to send messages to all the other nodes, even if they are only following. Once a leader node receives a sync message from a follower node, it gets discarded because there is no signature, which (I think) is what is preventing a follower nodes from getting any more messages.

To fix this, it would require me to either

a) also distribute the private key to a reading node, which I cannot do or
b) master nodes should accept all messages of type "sync step 1" and "sync step 2".

Again, this comes from my crude understanding of how the Yjs protocol works under the hood.

Is there a solution for this?

Thanks so much!

**Comment by dmonad** [comment]
Yep, there is a way to implement authentication in Yjs.

You can grant either read or write access.
The idea is that a Yjs instance checks the authorization of all connected clients. Here is a basic example of authentication using passwords:

```
Y({
  connector: {
    name: ..,
    auth: 'superSecretPassword', // you can also put a JSON object here
    checkAuth: function (password) {
      return Promise(function (resolve, reject) {
        if (password === 'superSecretPassword') {
          resolve('write') // alternatively 'read' for read-only access
        } else {
          reject('Guess again')
        }
      })
    }
  }
})
```

'superSecretPassword' is sent to every connected client. Make sure that this is only sent to a trustworthy party.
checkAuth checks the password and returns a promise. Currently Yjs supports read-write and read-only access.
I assume you use the websockets-client connector. Here is a short tutorial on how to implement google authentification.

Adapt y-websockets-server:

```js
Y({
  connector: {
    // no auth required for the server
    checkAuth: function (idToken) {
      return checkGoogleIdToken(idToken) // using the 'google-id-token-verifier' package
    }
  }
})```

Client side:
```js
Y({
  connector: {
    // The validity of the server is already checked by the ssl certificate
    auth: idToken // send the verified idToken provided by the google auth method
  }
})
```

**Comment by dmonad** [comment]
I think the implemented auth method may be useful for you. You should be able to implement what you want to do. 

I forgot to mention:

```js
checkAuth: function () {
   return Promise.resolve('read')
}
```

always grants read-only access

**Comment by pgte** [comment]
@dmonad thank you, this helps a lot!
I'm now using this feature not to exchange a secret, but to send an auth token which is the signature of the peer id (which is secure in IPFS).
To validate that I need to know the Yjs peer user id inside my `options.connector.checkAuth` function. Would this be possible?

**Comment by dmonad** [comment]
I suggest that you set:

```js
auth: {
  userId: userInformation,
  secret: '...'
}
```

Then the userId is transmitted to all connected peers.

**Comment by pgte** [comment]
That way I think I'll be vulnerable to repetition attacks, since I can't have a way to verify the node id..

**Comment by dmonad** [comment]
In yjs@13.3.2 checkAuth also provides sender information as the third parameter.

```
checkAuth = function (authInformation, yjsInstance, sender) {}
```

**Comment by pgte** [comment]
@dmonad fantastic, works great, thanks so much! 👍
