### ISSUE TITLE
multiple rooms are not synced when filling room with data before sync between client and server

### ISSUE THREAD

**Issue by Feasze** [y-js/yjs#80]
I have an problem when connecting to multiple rooms with Y from the client to the websocket-server.
I am using the y-memory and the y-websocket-client in the browser. On the server-side when creating a room I fill the room with data before I allow the client to connect. This is working fine if I connect to 1 room at a time, but not when I am connecting to multiple rooms. 
After the connection some of the rooms are not synced. The data I set in the node-server are not synced with the client.
i've made an example that shows the exact problem. You can find it on [my git repo here](https://github.com/Feasze/y-multi-room-test)

**Comment by dmonad** [comment]
This was a Yjs bug. Some time ago I published a bit experimental feature and it seems to break your project. I removed that feature for now and I'm going to publish it again when it is stable.

This was fixed in Yjs@12.3.3

**Comment by Feasze** [comment]
Thank you 😋
