### ISSUE TITLE
How can I change property's key name on y-map

### ISSUE THREAD

**Issue by kifhan** [y-js/yjs#81]
I've tried following way. But it seems doesn't work as I expected.

```js
y.share.map.set(newPath, y.share.map.get(oldPath))
y.share.map.delete(oldPath)
```

it crashes when property is y data type.

It seems Y-Map set is only takes TypeDefinition and creates a new DataType object.
If is so, I think I have to clone all deltas to the new object.
Is there any easy way to do this?

**Comment by dmonad** [comment]
This is the expected behavior. You can either insert a fresh type, or any stringifyable object.

**Comment by dmonad** [comment]
You have to create a copy of your object or use a different shared data structure.
