### ISSUE TITLE
event with user

### ISSUE THREAD

**Issue by pgte** [y-js/yjs#83]
Currently, when observing mutation events, the event does not contain any information about the user that started it. Is it possible to know the user that is responsible for the operation?

If so, I'm willing to submit a PR if you give me some pointers.. :)

**Comment by dmonad** [comment]
Hey Pedro,

In y-array and y-map you can get the userid of the user who made the change by calling:

array._content[position].id[0]

In y-map:

map.map[name].id[0]

But note that the userid will change across multiple sessions.

Best,
Kevin
