### ISSUE TITLE
Feature request: insert a new y.map with one observeDeep trigger

### ISSUE THREAD

**Issue by boschDev** [y-js/yjs#85]
By creating a new item I insert a Y.Map into an Y.Array. After this the content will be enterd in the object. The problem is that there is an save command in the observeDeep what by evry cache will trigger. By inserting a new item the load will rise and the log will show multiple save debounces. Is it possable that there wil be a function like:

```javascript
var newMap = new Y.Map.Builder();
newMap.set('id', 1);
newMap.set('title', 'Test Title');
Yarray.insert(1, [newMap]);
```

So that there will be only one trigger by the observeDeep. What also would be very nice is a new parameter by an Y.Map set and a Y.Array insert. This parameter is a bool (default false) which could be caled isInternal. This could be used for in the observe event for e.g. ordering / skipping

**Comment by dmonad** [comment]
Hi @boschDev 
I have been working on a new Yjs release for quite some time now. Next week I'm gonna publish a new beta release with some changes that might interest you.

Here is a sum up: https://www.evernote.com/l/Ai70hgBc6mtOBanhPLWodktpH4RQ7NqpBJ4

I have been working on a new event system with some kind of transaction support. Changes inside a transaction are executed atomically, therefore only trigger one event. Check the section about transactions in the note above.

Thanks for your idea though! It would have solved the issue in another way.
