### ISSUE TITLE
UndoManager with two people editing the same sentence in y-xml

### ISSUE THREAD

**Issue by twiss** [y-js/yjs#87]
In the html-editor example, if I type "Lorem ipsum dolor sit amet." in window 1, and then in window 2 replace "dolor" with "test", and then in window 1 undo+redo, it becomes "Lorem ipsum testdolor sit amet."

And if I type it, and then in a second window make "dolor" bold (using Control+B in Chrome), and then undo+redo in the first window, it becomes: "Lorem ipsum **dolor**Lorem ipsum dolor sit amet."

Ideally, I think, the undo should delete the whole sentence even though it was modified?

I realize that collab + HTML + undo&redo is a really difficult problem (I just tried it in GDocs and it choked on redo, heh.), but do you think it's possible to fix this? In any case, thanks for all your work on Yjs!

**Comment by dmonad** [comment]
Hey @twiss 
I have been heavily working on undo-redo in Yjs. Check out the html-editor demo in Yjs@v13. But note that  I will likely break the API a few more times
