### ISSUE TITLE
Problems with examples

### ISSUE THREAD

**Issue by kidinamoto01** [y-js/yjs#88]
Hello, there

I am testing examples of Yjs. Unfortunately, the `define` function is not available. 
I installed yes package with NPM

`const Y = require('yjs')
require('y-memory')(Y) 
require('y-websockets-client')(Y)
require('y-array')(Y)
require('y-map')(Y)

var y = new Y({
  db: {
      name: 'memory'
  },
  connector: {
    name: 'websockets-client',
    room: 'chat-example'
  }
})
window.yChat = y
let chatprotocol = y.define('chatprotocol', Y.Array)`

Thanks so much for any advice.

**Comment by dmonad** [comment]
Hey @kidinamoto01 You are looking at the examples for Yjs@v13. Check the examples for the stable release v12: https://github.com/y-js/yjs/tree/8739fd3a9c671c738fe0f31f1dc03193da776223/Examples
