### ISSUE TITLE
Monaco install issues

### ISSUE THREAD

**Issue by michaelerobertsjr** [y-js/yjs#89]
Please let me know what we are doing wrong.  We are trying to implement monaco using the example file but running into a couple of issues:

**Installing the dependencies** - I was able to use npm and bower and get things wired up but it was not easy.  I am not sure if rollup was supposed to have a build task for the examples, etc.  Can you explain what are the requirements to build and run the examples?

**After setting up, getting a runtime error** - After setup I am getting an error in chrome:
```
VM2785 loader.js:1130 Uncaught Error: Can only have one anonymous define call per script file
    at ModuleManager.enqueueDefineAnonymousModule (VM2785 loader.js:1130)
    at _defineFunc (VM2785 loader.js:1595)
    at VM2788 y-websockets-client.js:7
    at VM2788 y-websockets-client.js:7
ModuleManager.enqueueDefineAnonymousModule @ VM2785 loader.js:1130
_defineFunc @ VM2785 loader.js:1595
(anonymous) @ VM2788 y-websockets-client.js:7
(anonymous) @ VM2788 y-websockets-client.js:7
VM2785 loader.js:1154 Duplicate definition of module 'vs/editor/editor.main'
ModuleManager.defineModule @ VM2785 loader.js:1154
ModuleManager._onLoad @ VM2785 loader.js:1244
(anonymous) @ VM2785 loader.js:1413
OnlyOnceScriptLoader.triggerCallback @ VM2785 loader.js:562
(anonymous) @ VM2785 loader.js:556
loadEventListener @ VM2785 loader.js:588
```
Here is an example of our implementation: [index.html](https://gist.github.com/michaelerobertsjr/d21f3b0e63c6fce710ee11df5d37f6b8)

**Comment by dmonad** [comment]
Hi @michaelerobertsjr Can you explain to me where you got the examples, and which Yjs version you are using?
You can download one of the 12.x.x releases and run `bower install && npm install` in the examples folder.
Note: The version 13.x.x of Yjs is still in beta. Monaco does not work yet

**Comment by michaelerobertsjr** [comment]
Thanks for following up, we've moved on to using a ShareDB implementation since Monaco is not yet supported.
