### ISSUE TITLE
How to reinit the existing yjs object?

### ISSUE THREAD

**Issue by KrishnaPG** [y-js/yjs#91]
I am doing `Y({ ... user.preferredRoom})` when a user logins onto the site.

With an existing `Yjs` object, when the currently logged-in user changes, I want to change the room accordingly. So, should I destroy the existing `Yjs` object and call `Y()` again with new room or is there some other way?

When the current user logs out, I want to clean the current `Yjs` object, what is the right way?

Calling `y.destroy()` and then calling `Y()` again is not working. The second `Y()` call promise is never getting resolved.

**Comment by dmonad** [comment]
> Calling y.destroy() and then calling Y() again is not working. The second Y() call promise is never getting resolved.

This is very weird and should not happen. You should be able to open the same rooms in several Yjs objects. Which connector are you using?

**Comment by gudegiz** [comment]
````
		return Y({
			db: {
				name: 'indexeddb' // use indexeddb database adapter instead for offline apps
			},
			connector: {
				name: 'webrtc', // use webrtc connector
				room: Room // clients connecting to the same room share data
			},
			sourceDir: null,
			share: {
				store: 'Map' // y.share.store is of type y-map
			}
		})
````

**Comment by KrishnaPG** [comment]
````
		return Y({
			db: {
				name: 'indexeddb' // use indexeddb database adapter instead for offline apps
			},
			connector: {
				name: 'webrtc', // use webrtc connector
				room: Room // clients connecting to the same room share data
			},
			sourceDir: null,
			share: {
				store: 'Map' // y.share.store is of type y-map
			}
		})
````

**Comment by dmonad** [comment]
Does it work when you don't use indexeddb?
