### ISSUE TITLE
How is this different from ShareDB

### ISSUE THREAD

**Issue by houshuang** [y-js/yjs#93]
ShareDB is a relatively well-known project with many of the same goals as Y-js. It would be useful for visitors to see a comparison with ShareDB (and any other relevant projects) in the README or on the wiki. Perhaps the two projects are very similar, just two implementations of the same idea. Or perhaps there are differences leading a user to choose one over the other. Thanks!

**Comment by KrishnaPG** [comment]
Also, I do not see support for WebRTC in ShareDB, unless I am mistaken.

**Comment by houshuang** [comment]
This is very useful, and could probably be copied and pasted into a README or the wiki.

ShareDB certainly supports WebRTC though.
