### ISSUE TITLE
Where can I find a changelog?

### ISSUE THREAD

**Issue by kifhan** [y-js/yjs#97]
It was on README before version 13 but now I can't find it.
Y-js website only show changelog before version 13.
Ofcourse I can track this by search on commit history but can you Please write a changelog to understand what difference was made in version 13?
Thank you.

**Comment by dmonad** [comment]
Yep I will definitely do that. In the meantime you can get a general idea by looking at #99 The interface is still changing. But I will publish a changelog for the first alpha.
