### ISSUE TITLE
html-editor example no longer syncs across two tabs

### ISSUE THREAD

**Issue by twiss** [y-js/yjs#98]
Maybe I'm doing something wrong, but I can't get the html-editor example to sync what I type across two tabs. I remember it working before I updated yjs. I don't see any errors, and the y-websockets-server output looks as follows:

```bash
> y-websockets-server@10.0.0-2 start /home/daniel/y-websockets-server
> DEBUG=y*,-y:connector-message node ./src/server.js

Running y-websockets-server: port: 1234, redis: null 
  y-websockets-server User "Fg_YNNFjuofGy8r2AAAA" joins room "htmleditor" +0ms
  y-websockets-server User "E0CYoBUkJpYWRqM8AAAB" joins room "htmleditor" +8s
```

Nothing happens in the console when I type something in the example.

**Comment by dmonad** [comment]
Hey, I just fixed that. Pull the latest y-websockets-server ;)

**Comment by twiss** [comment]
Thanks! :+1:
